# IPPrefix Resources for OAI gNB — Apply to Management Cluster
# These define IP address pools that IPAM allocates from
# The key link: networkInstance.name must match Interface.spec.networkInstance.name
---
# IP Pool for N2 (Control Plane - gNB to AMF)
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: oai-control-pool
  namespace: default
  labels:
    nephio.org/purpose: control
    nephio.org/network-type: n2
spec:
  prefix: 10.1.2.0/24
  networkInstance:
    name: vpc-control
  labels:
    nephio.org/address-family: ipv4
    nephio.org/cluster-name: my-ran
---
# IP Pool for N3 (User Plane - gNB to UPF)
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: oai-userplane-pool
  namespace: default
  labels:
    nephio.org/purpose: userplane
    nephio.org/network-type: n3
spec:
  prefix: 10.1.3.0/24
  networkInstance:
    name: vpc-userplane
  labels:
    nephio.org/address-family: ipv4
    nephio.org/cluster-name: my-ran
---
# IP Pool for RU (Fronthaul - gNB to Radio Unit)
apiVersion: ipam.resource.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: oai-fronthaul-pool
  namespace: default
  labels:
    nephio.org/purpose: fronthaul
    nephio.org/network-type: ru
spec:
  prefix: 10.2.6.0/24
  networkInstance:
    name: vpc-fronthaul
  labels:
    nephio.org/address-family: ipv4
    nephio.org/cluster-name: my-ran
