# Whereabouts PackageVariant for my-ran cluster
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: whereabouts-my-ran
  namespace: default
spec:
  upstream:
    repo: nephio-blueprints-approachb
    package: networking/whereabouts-ipam
  downstream:
    repo: nephio-my-ran
    package: whereabouts-ipam
