# OAI CUCP PackageVariant
# Deploys the CU Control Plane (interfaces: e1, f1c, n2)
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-cucp-ran
spec:
  upstream:
    repo: catalog-workloads-oai-ran-custom
    package: pkg-example-cucp-bp
  downstream:
    repo: nephio-ran
    package: oai-ran-cucp
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - group: infra.nephio.org
    version: v1alpha1
    kind: WorkloadCluster
    name: ran
